APK building workflows (on demand and CI one) (#7)
Fix CI workflow so that it can properly build APKs after every commit.

Additionally, add one more workflow which can build any repo/branch without forking them.

Both of them upload the built APK when done; only the CI one is set to run

Issue link: https://github.com/Cloud-City-RS/OMNTelcoMetrics/issues/3

If we revisit this later on, the new key has to be generated by using the `keytool` tool, and then Base64'd and that has to be put in the Repo's Secrets as `KEYSTORE`, the key alias as `KEYALIAS` and the store/key passwords as `STOREPASSWORD` and `KEYPASSWORD` respectively.

The command for generating the new keystore is:
```
keytool -genkeypair -v -keystore new-keystore.jks -keyalg RSA -keysize 2048 -validity 10000 -alias cloudcity
```
and that will generate a  keystore with 'cloudcity' key alias

<!-- This is an auto-generated comment: release notes by coderabbit.ai -->

## Summary by CodeRabbit

- **New Features**
	- Introduced a new workflow for manually building Android APKs with customizable inputs.
	- Updated existing workflow to focus on building debug APKs, enhancing output detail during the process.
  
- **Bug Fixes**
	- Improved file handling in APK build processes to accommodate variations in file names.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->


* Add new workflow to test building the APK

* Touch-up to the AndroidCI workflow

Apart from both the build 'release' and 'debug' APKs steps being called "build release APK",
I've also added the --info flag for them to print out more verbose information, since they're failing
on where the actual APKs ended up.

Currently, the workflow is failing with this error:

Run echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  mkdir upload
  mv app/build/outputs/apk/debug/app-debug.apk ./upload/omnt-debug.apk
  mv app/build/outputs/apk/release/app-release.apk ./upload/omnt-release.apk
  mv app/build/spdx/release.spdx.json ./upload/release.spdx.json
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
mv: cannot stat 'app/build/outputs/apk/debug/app-debug.apk': No such file or directory
Error: Process completed with exit code 1.

* Change the workflow to work with the namechanged files

It was expecting app-debug.apk and app-release.apk but obviously that won't work
for CloudCity_OpenMobileNetworkToolkit_debug_0.3

so let's just make the debug thing work for *debug*.apk and the release work for *release*.apk

* Change default repo to cloudcity's repo

The on-demand workflow defaulted to some sunflower repo; let's default to this repo instead

* Get rid of artefact renaming before uploading

* Update .github/workflows/build-apk.yaml

Failfast before uploading artefacts if no files were found.

Co-authored-by: coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
Signed-off-by: RkShaRkz <darksidemetatron@gmail.com>

* Update .github/workflows/build-apk.yaml

Add gradle caching and improve error detection; also limit workers to 2

Co-authored-by: coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
Signed-off-by: RkShaRkz <darksidemetatron@gmail.com>

---------

Signed-off-by: RkShaRkz <darksidemetatron@gmail.com>
Co-authored-by: coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>