Fix some build problems (#8)
* Add new workflow to test building the APK

* Touch-up to the AndroidCI workflow

Apart from both the build 'release' and 'debug' APKs steps being called "build release APK",
I've also added the --info flag for them to print out more verbose information, since they're failing
on where the actual APKs ended up.

Currently, the workflow is failing with this error:

Run echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  mkdir upload
  mv app/build/outputs/apk/debug/app-debug.apk ./upload/omnt-debug.apk
  mv app/build/outputs/apk/release/app-release.apk ./upload/omnt-release.apk
  mv app/build/spdx/release.spdx.json ./upload/release.spdx.json
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
mv: cannot stat 'app/build/outputs/apk/debug/app-debug.apk': No such file or directory
Error: Process completed with exit code 1.

* Change the workflow to work with the namechanged files

It was expecting app-debug.apk and app-release.apk but obviously that won't work
for CloudCity_OpenMobileNetworkToolkit_debug_0.3

so let's just make the debug thing work for *debug*.apk and the release work for *release*.apk

* Stop using git hash in APK file name and About screen

I need to figure this one out better, but gradle can't find git and is failing the build
because of that.
So this commit just comments those usages out so that things can be built.

* Add the important reminder

* Address CR comments

---------

Signed-off-by: RkShaRkz <darksidemetatron@gmail.com>