Touch-up to the AndroidCI workflow
Apart from both the build 'release' and 'debug' APKs steps being called "build release APK",
I've also added the --info flag for them to print out more verbose information, since they're failing
on where the actual APKs ended up.

Currently, the workflow is failing with this error:

Run echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  mkdir upload
  mv app/build/outputs/apk/debug/app-debug.apk ./upload/omnt-debug.apk
  mv app/build/outputs/apk/release/app-release.apk ./upload/omnt-release.apk
  mv app/build/spdx/release.spdx.json ./upload/release.spdx.json
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
    JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64
mv: cannot stat 'app/build/outputs/apk/debug/app-debug.apk': No such file or directory
Error: Process completed with exit code 1.